function Hd = Filtro60HzButterworth
%FILTRO60HZBUTTERWORTH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 20-May-2018 23:00:59

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

Fpass1 = 50;          % First Passband Frequency
Fstop1 = 55;          % First Stopband Frequency
Fstop2 = 65;          % Second Stopband Frequency
Fpass2 = 70;          % Second Passband Frequency
Apass1 = 1;           % First Passband Ripple (dB)
Astop  = 60;          % Stopband Attenuation (dB)
Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
